### ISSUE TITLE
Cannot import Arn as Maven dependency

### ISSUE THREAD

**Issue by MrCreepyCraft32** [efekos/Arn#1]
**Bug Details**

Impossible to import Arn as a Maven dependency

```
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download maven-metadata-efekosdev.xml [https://efekos.dev/maven/]
[WARNING] Failed to download arn-paper-0.4.pom [https://efekos.dev/maven/]
[WARNING] Failed to download arn-paper-0.4.pom [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download arn-paper-0.4.pom [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download arn-paper-0.4.pom [https://repo.maven.apache.org/maven2/]
[WARNING] The POM for dev.efekos.arn:arn-paper:jar:0.4 is missing, no dependency information available
[WARNING] Failed to download arn-paper-0.4.jar [https://efekos.dev/maven/]
[WARNING] Failed to download arn-paper-0.4.jar [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download arn-paper-0.4.jar [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download arn-paper-0.4.jar [https://repo.maven.apache.org/maven2/]
Cannot resolve dev.efekos.arn:arn-paper:0.4
```

**To Reproduce the Bug:**

Add Arn as a Maven dependency, then try to download it

**Comment by efekos** [comment]
I forgot to upload the new dependencies to the server. I'll upload it and close this issue in a few minutes.

**Comment by MrCreepyCraft32** [comment]
> I forgot to upload the new dependencies to the server. I'll upload it and close this issue in a few minutes.

To be honest I tried using "older" versions too, and it didn't work 😅

I'm gonna try again, thanks !

**Comment by MrCreepyCraft32** [comment]
It's still not working, but when editing my import to use version "0.4.0-SNAPSHOT" instead of "0.4", I'm getting this error :
```
[WARNING] Failed to download maven-metadata-efekosdev.xml [https://efekos.dev/maven/]
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download maven-metadata-papermc-repo.xml [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download maven-metadata-local.xml [file://C:\EfekosDev\Maven/]
[WARNING] Failed to download maven-metadata-efekosdev.xml [https://efekos.dev/maven/]
[WARNING] Failed to download maven-metadata-papermc-repo.xml [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download arn-root-0.4-SNAPSHOT.pom [https://efekos.dev/maven/]
[WARNING] Failed to download arn-root-0.4-SNAPSHOT.pom [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download arn-root-0.4-SNAPSHOT.pom [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download arn-root-0.4-SNAPSHOT.pom [file://C:\EfekosDev\Maven/]
[INFO] Validation error:

[ERROR] Failed to read artifact descriptor for dev.efekos.arn:arn-paper:jar:0.4.0-SNAPSHOT
[ERROR] [server] Maven transfer artifact problem: dev.efekos.arn:arn-root:pom:0.4-SNAPSHOT
Cannot resolve dev.efekos.arn:arn-root:0.4-SNAPSHOT
```
It's looking for arn-root, but only arn-common is on your server, maybe this is the reason?

**Comment by efekos** [comment]
`arn-root` isn't on my local repo either, it isn't even uploaded to anywhere when you deploy the project. Assuming that you used `arn-paper` or `arn-spigot` and didn't add `arn-root` manually. It shouldn't try to find `arn-root`.

**Comment by MrCreepyCraft32** [comment]
> `arn-root` isn't on my local repo either, it isn't even uploaded to anywhere when you deploy the project. Assuming that you used `arn-paper` or `arn-spigot` and didn't add `arn-root` manually. It shouldn't try to find `arn-root`.

True, I didn't add it myself in my pom file.
I thought you splitted the dependency, with the `arn-root` base and the `arn-paper` would implement it with a few differences from the spigot version

(Sorry for my poor english, it is not my native language)

**Comment by efekos** [comment]
I just found out why it works on my machine. I once deployed an old version of Arn where `arn-root` was also deployed, and my IDE saved it to .m2 folder in the user folder when installing it again. So my IDE thought `arn-root` was present and didn't give me any errors this whole time :/. I'll change the configuration to make it also deploy `arn-root`.

**Comment by efekos** [comment]
`arn-root` is now uploaded to the server and everything should be fine.
